spring.application.name=equipment-service

spring.profiles.active=dev

documentation.application.description=@project.description@
documentation.application.version=@project.version@

spring.jpa.hibernate.naming.physical-strategy=io.github.rafaviv.yakubackend.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy