server.port=8084
spring.application.name=subscription-service
spring.config.import=optional:file:.env[.properties]

spring.profiles.active=dev

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
stripe.success.url=${STRIPE_SUCCESS_URL}
stripe.cancel.url=${STRIPE_CANCEL_URL}

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7

# CORS Configuration
spring.graphql.cors.allowed-origins=https://front-opensource.web.app
spring.graphql.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.graphql.cors.allowed-headers=Origin,Accept,X-Requested-With,Content-Type,Authorization,Access-Control-Request-Method,Access-Control-Request-Headers
spring.graphql.cors.allow-credentials=true