spring.datasource.url=jdbc:postgresql://localhost:5432/yaku_equipment
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
debug=true

spring.kafka.bootstrap-servers=localhost:9092